name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Esta seção pode ser mantida, ela não causará erro,
      # apenas não fará nada se os secrets não existirem.
      - name: Write Keys
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
            echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> keystore.properties
            echo androidKeyAlias='${{ secrets.ALIAS }}' >> keystore.properties
            echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
            echo androidStoreFile='key.jks' >> keystore.properties
            echo "${{ secrets.KEY_STORE }}" | base64 --decode > app/key.jks
          fi

      # --- AJUSTE 1: MUDADO DE assembleRelease PARA assembleDebug ---
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Get Version Name
        id: version
        run: |
          VERSION_NAME=$(grep "versionName" app/build.gradle | awk -F '"' '{print $2}' | head -n 1)
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

      # --- AJUSTE 2: MUDADO O CAMINHO PARA A PASTA debug ---
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-${{ steps.version.outputs.version_name }}
          path: app/build/outputs/apk/debug/*.apk
